probot/create-probot-app

README.md
bin/create-probot-plugin.js
package-lock.json
package.json

Once the project has been scaffolded, install the npm dependencies by running `npm install --prefix DESTINATION` within Node.
Will close #2

📦 Install npm dependencies

---

README.md

This seems like a great use case for `npx`, so i thought i would add an option in the README to show users how they might get started with either `npm` or `npx`!

add npx option

---

bin/create-probot-app.js

Goes with https://github.com/probot/template/pull/27

add year from current date to fill in (c) year in license template

---

README.md

Replace example with link to docs

---

bin/create-probot-app.js

This is a PR against #28 that implements the suggestion of making `--typescript` an alias for `--template=typescript`, and having that look for `https://github.com/probot/template-typescript.git`.

 Make `--typescript` and alias for `--template=typescript`

---

templates/basic-js/index.js
templates/checks-js/index.js
templates/deploy-js/index.js
templates/git-data-js/index.js

Closes #54 
@JasonEtco I also updated the other JS examples!

Add type hints for javascript examples

---

templates/basic-js/package.json
templates/basic-ts/package.json
templates/checks-js/package.json
templates/deploy-js/package.json
templates/git-data-js/package.json

Greenkeeper/default/nock 11.6.0

---

script/test
src/create-probot-app.ts

fix: Escape a limited set of symbols

---

.github/CODEOWNERS
.gitignore
package-lock.json
package.json
script/test
templates/basic-js/package.json
templates/basic-ts/package.json
templates/checks-js/package.json
templates/deploy-js/package.json
templates/git-data-js/package.json

- Test in temp directory using `mktemp`. See https://unix.stackexchange.com/a/84980
- Remove temp directory after project testing
- Removed `tmp` entry from `.gitignore`

chore(test): Test in unique directory outside project root

---

templates/basic-ts/README.md
templates/basic-ts/nodemon.json
templates/basic-ts/package.json
templates/basic-ts/tsconfig.json

- Add new command to build and relaunch automatically
- Up to date and stricter tsconfig.json

fix: typescript template improvement 

---

.github/workflows/test.yml
.gitignore
package-lock.json

My understanding is that the `tmp` folder is created by running the tests, it should not be committed to the code

build(gitignore): tmp

---

.github/dependabot.yml

Ref: https://github.com/probot/create-probot-app/pull/305#issuecomment-754233780

ci(dependabot): keep templates dependencies up to date

---

package-lock.json
package.json

Ref: https://github.com/probot/create-probot-app/pull/299#issuecomment-754798319

fix: remove redundant probot dependency

---

.github/workflows/test.yml
README.md
script/test

Ref: https://github.com/probot/create-probot-app/issues/309#issuecomment-754871569

ci(test): use matrix strategy to test against all maintained node versions

---

src/create-probot-app.ts
templates/basic-js/package.json
templates/basic-ts/package.json
templates/checks-js/package.json
templates/deploy-js/package.json
templates/git-data-js/package.json

Given that the user already has the faculty to decide in which folder
to create the application, should also be allowed to disable git
initialization too.

feat: add --no-git-init option

---

src/helpers/init-git.ts

This should help making the git repo creation process more transparent.

fix: add logging to init-git helper

---

src/create-probot-app.ts
src/helpers/filesystem.ts
src/helpers/user-interaction.ts

Ref: 
- https://github.com/probot/create-probot-app/issues/322
- https://github.com/probot/create-probot-app/issues/315

fix: add some type safety

---

package-lock.json
package.json
src/helpers/user-interaction.ts

build(deps): bump commander from 6.2.1 to 7.0.0

---

package-lock.json
package.json

fix: add npm to dependencies

---

src/helpers/filesystem.ts
src/helpers/user-interaction.ts
templates/basic-js/__description__.txt
templates/basic-ts/__description__.txt
templates/checks-js/__description__.txt
templates/deploy-js/__description__.txt
templates/git-data-js/__description__.txt

- also: fix --show-templates CLI option
Fixes: https://github.com/probot/create-probot-app/issues/138

fix: add template description prompting user for choice

---

src/helpers/init-git.ts

Fix: https://github.com/probot/create-probot-app/issues/356

fix: ignore initialization-breaking errors in git-init module

---

.github/workflows/test.yml
.gitignore
package.json
script/test-template.sh

Fix https://github.com/probot/create-probot-app/issues/350

chore(ci): use (Linux/macOS portable) temporary folder for template tests

---

package.json
script/make-executable.ts
script/test-template.sh
src/run-tests.ts

Fix: https://github.com/probot/create-probot-app/issues/348

fix: move some tests from Bash to TS, add check to package.json
