probot/create-probot-app

README.md, bin/create-probot-app.js, package-lock.json, package.json
=> Rename plugin to app

bin/create-probot-app.js, package-lock.json, package.json
Use the Standard linter, as per https://github.com/probot/probot/issues/235.
Installs the linter, removes `xo` and `eslint-plugin-probot` and fixes all the linting errors/warnings in `create-probot-app.js`.
=> Use the standard linter

bin/create-probot-app.js
Changes:
* Updated CLI option for package name to ask the name of the app
* Updated CLI flags to match new verbiage 
* '-a' was taken for author, let me know your thoughts on this change/whether it should remain '-p'
* Update package name prompt to reflect change to \'app\' name
=> Update verbiage of pkg name command option

bin/create-probot-app.js, package.json
If the user types in an invalid **package name** when the **create-probot-app** asks for an app name then the app throws an error of invalid package name while executing **npm start**.
To avoid this I have added the validation of app name while asking using the package [validate-npm-package-name](https://www.npmjs.com/package/validate-npm-package-name)
=> Add validation for appname to be a well formed npm package name

README.md
This adds `npx` and `yarn` commands to the README, but still points to the docs for getting started.
=> add invocations to readme

bin/create-probot-app.js
=> update description variable name

README.md, bin/create-probot-app.js
Fixes #27 and #26 
This adds an option for scaffolding new apps with a TypeScript template (repo to be created). There's a better way to write this that I'm not seeing at the moment, but it works.
=> Add option for scaffolding with a typescript template

bin/create-probot-app.js, package.json
This PR adds a camel-cased version of the app's title to the scaffolding variables, so that we can use it when, for example, [creating a test](https://github.com/probot/template/pull/74).
I'm not a huge fan of the naming for `answers.variable`, but since it went along with the discussion in that PR I figured it was good enough to show what I was thinking. Open to opinions on better naming 👍
=> Add camel-cased app name

bin/create-probot-app.js, package.json
To help with testing out changes to various templates (e.g.: https://github.com/probot/template/pull/77/), I thought we should add an option to specify a branch. Turns out [scaffold supports specifying a branch name](https://github.com/boneskull/egad#basic-usage) that defaults to master, so this PR adds a command line flag to allow users to provide this option.
```sh
➜   npx probot-app --help
Options:
...
-b, --branch <branch-name>  Specify a branch (default: master)
```
=> Add option to scaffold from a specific branch of a repository

templates/basic-ts/test/index.test.ts
Since done isn't called in the example test we never reach the callback where we do the expect assertion causing the tests to pass even when they shouldn't since the test suite doesn't know that we need to wait for the callback to called.
By taking the `done` callback in as argument in the test function we signal to the test suite that this test should fail is `done()` isn't called.
See https://jestjs.io/docs/en/asynchronous.html for further reading.
=> Make sure to call `done()` in a async test

templates/checks-js/index.js, templates/checks-js/test/fixtures/check_run.created.json, templates/checks-js/test/index.test.js
This prevents GitHub from reporting:
`{app-name} Successful in -1m`
See https://github.com/probot/probot/issues/803
=> Add started at

script/test
This was fun to track down. Travis is [prepending](https://github.com/travis-ci/travis-build/blob/4a8f957ecddf3ee5b3ba94e1e525c95fb064a98f/lib/travis/build/script/node_js.rb#L26) a relative path - `./node_modules/.bin` - to $PATH.
Running binaries/commands when outside project root would lead to bad path references.
Because semantic-release installs NPM, the NPM binary is always referenced from the root of the project (note: the project root is where the CI shell is instantiated). But once we enter any other directory, that relative reference is bad.
fixes #91
=> fix: remove prepended `./node_modules/.bin` from $PATH

.github/CODEOWNERS
I have been unable to merge PRs - even with maintainer privileges for this repo. I can't see the branch protection settings, but with the presence of a CODEOWNERs file, I'm guessing the option requiring PRs to be reviewed by a  [CODEOWNER](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners) is enabled.
=> chore: Add @MaximDevoir as CODEOWNER

templates/basic-js/package.json, templates/basic-ts/package.json, templates/checks-js/package.json, templates/deploy-js/package.json, templates/git-data-js/package.json
I saw engines in package.json that is used a deprecated version of node
So I feel like that there should be updated to a maintenance version
=> chore: Update minimum node version

templates/basic-ts/package.json
Before this update, `npm install` fails.
=> fix(basic-ts): update dependency

.gitignore, README.md, templates/basic-js/index.js, templates/basic-js/package.json, templates/basic-js/test/index.test.js, templates/basic-ts/package.json, templates/basic-ts/src/index.ts, templates/basic-ts/test/index.test.ts, templates/checks-js/index.js, templates/checks-js/package.json, templates/checks-js/test/index.test.js, templates/deploy-js/index.js, templates/deploy-js/package.json, templates/deploy-js/test/index.test.js, templates/git-data-js/index.js, templates/git-data-js/package.json, templates/git-data-js/test/index.test.js
- For each template:
- fix deprecation warnings upgrading `package.json` + fixing units for latest Probot version usage
- fix app signatures, ref: https://github.com/probot/probot/issues/1286#issuecomment-744094299
- tentative small changes to `README.md` meant to reduce frictions for new users
Note to myself: final welcome message for TypeScript users should remind about the required `build` step, I'll open a dedicated issue for it
-----
[View rendered README.md](https://github.com/shaftoe/create-probot-app/blob/upgrade-to-v11/README.md)
=> fix: upgrade template apps to v11

src/create-probot-app.ts
At the moment it fails to properly show the folder when to cd into after installation:
```
Successfully created app.
Begin using your app with:
cd
npm start
```
This patch should fix it
=> fix: show correct folder on app creation

templates/basic-js/package.json, templates/basic-ts/package.json, templates/checks-js/package.json, templates/deploy-js/package.json, templates/git-data-js/package.json
probot/probot reads the `homepage` key from `package.json` during Probot App Setup to set the GitHub App Manifest's `url`, a required property to programmatically create GitHub Apps.
fixes: #346
=> fix: add `homepage` to each template's package.json file

.gitignore, script/test-template.sh, src/create-probot-app.ts, src/helpers/filesystem.ts, src/helpers/run-npm.ts, src/helpers/user-interaction.ts
I think the current logic dealing with `.gitignore` is broken, plus, I couldn't understand why we need to update its content if a file with same name is already available in the target folder.
In my opinion we should treat `.gitignore` as every other templated file in order to be idempotent, i.e. if the target file exists than skip creation all together.
=> BREAKING CHANGE: remove support for initializing on non-empty directories

package-lock.json, package.json, src/helpers/run-npm.ts
Apparently there's been some change in the logic of how NPM 7 deals with install target folder, this seems to work all right even though I'm not sure it's the best way to accomplish it.
=> fix(deps): bump npm from 6.14.11 to 7.5.2

templates/basic-js/package.json, templates/basic-ts/jest.config.js, templates/basic-ts/package.json
`testEnvironment` isn't configured in the basic-js template, so it defaults to `jsdom`. This configures it to `node`.
`testEnvironment` was configured in the `basic-ts` template, but Jest will only read configuration from one of its supported locations and in this case that's `jest.config.js`.
Running `npm test -- --debug` in a basic-ts app before:
Running `npm test -- --debug` in a basic-ts app after:
=> fix: jest testEnvironment for basic-js and basic-ts templates

.github/workflows/test.yml
Follow up to #814 which made the required Node version `>= 16.7.0`
=> ci: remove NodeJS 14+16
